server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: /opt/mnt_file/logs/eureka/
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D(ms)'
eureka:
  instance:
    hostname: localhost
    health-check-url-path: /health #健康检查地址
    status-page-url-path: /info #状态页的url地址
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka/
    healthcheck:
      enabled: true
  server:
    enableSelfPreservation: false           # 关闭自我保护模式（缺省为打开）
    evictionIntervalTimerInMs: 10000       # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    responseCacheUpdateIntervalMs: 5000   #eureka server刷新readCacheMap的时间，默认30s 注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上

# LOGGING
logging:
    config: classpath:logback.xml

#eureka 访问密码保护
spring:
  security:
    user:
      name: xmfadmin
      password: eureka-xmfp23dw
      roles: admin